Running python manage.py dumpdata attached to terminal... up, run.1
python: can't open file 'manage.py': [Errno 2] No such file or directory
